### ISSUE TITLE
无法限制注册

### ISSUE THREAD

**Issue by Stardust-minus** [evcloud/evcloud_dev#13]
![image](https://user-images.githubusercontent.com/52093397/154244230-8379f934-fb3d-4722-a439-c6123e4543bd.png)

在该界面点击注册可以显示该提示，阻拦用户注册。

但如果点击忘记密码之后，则可以通过点击右上角注册的方式进入系统。

![image](https://user-images.githubusercontent.com/52093397/154244354-01851ff9-873a-45ce-ba7e-878c6d501c76.png)
![image](https://user-images.githubusercontent.com/52093397/154244379-7198362c-7d0c-4ce7-9865-41ea3e2c576d.png)

**Comment by wangyushun** [comment]
现在注册功能可以通过配置文件参数“USE_REGISTER_USER”开启或关闭。
